### ISSUE TITLE
无法在LSPatch等寄生环境中使用

### ISSUE THREAD

**Issue by Runzelee** [Xposed-Modules-Repo/com.close.hook.ads#1]
在LSPatch中使用时，用户应用列表点击App弹出模块尚未被激活toast

**Comment by lovejiuwu** [comment]
请使用LSPosed框架激活后使用
LSPatch等免root框架无法使用此模块



---原始邮件---
发件人: "Runze ***@***.***&gt;
发送时间: 2024年1月20日(周六) 晚上11:48
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Xposed-Modules-Repo/com.close.hook.ads] 无法在LSPatch等寄生环境中使用 (Issue #1)




 
在LSPatch中使用时，用户应用列表点击App弹出模块尚未被激活toast

**Comment by Runzelee** [comment]
如果在LSPosed模块作用域中不用勾选系统框架，在LSPatch里可能也可以实现，希望能增加支持，感谢
